### ISSUE TITLE
运行遇错

### ISSUE THREAD

**Issue by briteming** [hashuser/yashmak#1]
hi.

root@sh:~/Yashmak# /usr/bin/python3.8 /root/Yashmak/server.py
Traceback (most recent call last):
  File "/root/Yashmak/server.py", line 292, in <module>
    server = yashmak()
  File "/root/Yashmak/server.py", line 228, in __init__
    self.load_config()
  File "/root/Yashmak/server.py", line 241, in load_config
    self.config['uuid'] = self.UUID_detect(set(list(map(self.encode, self.config['uuid']))))
  File "/root/Yashmak/server.py", line 281, in UUID_detect
    raise Exception
Exception
root@sh:~/Yashmak# python3 --version
Python 3.6.9
root@sh:~/Yashmak# which python3
/usr/bin/python3
root@sh:~/Yashmak# which python3.8
/usr/bin/python3.8
root@sh:~/Yashmak#

怎么解决？

**Comment by hashuser** [comment]
`File "/root/Yashmak/server.py", line 281, in UUID_detect`
根据这段，应该是UUID长度不符合标准
举个例子：
123456（不符合）
686a50a2-c877-4ee3-ad19-d39db7bb9209（符合）

**Comment by briteming** [comment]
但是我是运行了/usr/bin/python3.8 /root/Yashmak/server.py而已
我并没有去改过UUID的值。现在该怎么做呢？

**Comment by hashuser** [comment]
你配置文件填写了吗？第一次运行会在server.py目录生成一个config.json文件

**Comment by hashuser** [comment]
理论上如果用了官方一键安装脚本（仅支持Ubuntu），只要填写好配置文件reboot下就可以正常运行

**Comment by briteming** [comment]
root@sh:~/Yashmak# ps aux|grep  server.py
root      1509  0.0  0.4  14428   980 pts/0    S+   08:32   0:00 grep --color=auto server.py
root@sh:~/Yashmak# ls
blacklist.json  Cache  Certs  config.json  geoip.json  server.py
root@sh:~/Yashmak# cat config.json
{
    "geoip": "",
    "blacklist": "",
    "cert": "",
    "key": "",
    "uuid": [
        ""
    ],
    "listen": ""
}root@sh:~/Yashmak#

服务根本就未运行成功。配置文件该怎么写呢？

**Comment by briteming** [comment]
hi.
cat config.json
显示：
{
    "geoip": "./geoip.json",
    "blacklist": "./blacklist.json",
    "cert": "/root/Yashmak/Certs/server.crt",
    "key": "/root/Yashmak/Certs/server.key",
    "uuid": [
        "686a50a2-c877-4ee3-ad19-d39db7bb3708"
    ],
    "listen": "28399"
}

root@sh:~/Yashmak# ps aux|grep server.py
root       802  0.0  7.2  53836 17148 pts/0    S    21:58   0:00 python3.8 server.py
root       866  0.0  0.4  14428  1088 pts/2    S+   22:11   0:00 grep --color=auto server.py
root@sh:~/Yashmak# 
表明服务器端运行成功。

不过在本地机器mac上。
git clone https://github.com/hashuser/yashmak
cd yashmak
python3.8 local.py
但是怎么连上服务器的ip?在哪里设置？没看见设置的地方
